service: hrms
frameworkVersion: "3"

useDotenv: true

plugins:
    - serverless-offline

provider:
    name: aws
    stage: dev
    timeout: 15
    runtime: nodejs18.x
    region: us-east-1

functions:
    - ${file(./auth/function.yml)}
    - ${file(./employee/addEmployee/function.yml)}
    - ${file(./employee/function.yml)}
    - ${file(./department/function.yml)}
    - ${file(./dashboard/function.yml)}
    - ${file(./empType/function.yml)}
    - ${file(./organisation/function.yml)}
    